# 使用yaml做配置项
# 数据库配置项
db:
  mysql:
    dbname: "example"
    password: "root1234"
    username: "root"
    port: 3306
    host: "127.0.0.1"
log:
  # 默认路径是运行程序的目录
  #  logDirector: ./logging
  logInfoFilename: info.log
  logErrorFilename: error.log
  logMaxSize: 10
  logMaxBackups: 5
  logMaxAge: 10
  logLevel: info

jwt:
  enable: true
  signingMethod: "HS512"
  signingKey: "willow"
  expired: 7200
  store: "file"
  filePath: "data/jwt_auth.db"
  
es:
  index: fluent-bit*
  key: kubernetes.labels.job-name
  address: http://elasticsearch-master.logging:9200
  enable: true